# Generated by Django 4.1.5 on 2023-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_recommend_delete_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogged',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='date_recommended',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
