# Generated by Django 4.1.5 on 2023-02-12 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_alter_backlogged_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
