# Generated by Django 4.1.5 on 2023-03-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_playing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('outlet', models.CharField(max_length=200)),
            ],
        ),
    ]
