# Generated by Django 4.1.5 on 2023-04-19 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0011_goty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
