# Generated by Django 4.1.5 on 2023-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_playing_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='date_started',
            field=models.DateField(),
        ),
    ]
