# Generated by Django 4.1.5 on 2023-04-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_playing_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing', to='games.backlogged', unique=True),
        ),
    ]
