# Generated by Django 4.1.5 on 2023-04-20 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0019_alter_playing_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='backlog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playing', to='games.backlogged'),
        ),
        migrations.AlterUniqueTogether(
            name='backlogged',
            unique_together={('user', 'game')},
        ),
    ]
