# Generated by Django 4.1.5 on 2023-04-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_alter_playing_backlog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backlogged',
            unique_together=set(),
        ),
    ]
