# Generated by Django 4.1.5 on 2023-04-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_backlogged_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogged',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
