# Generated by Django 4.1.5 on 2023-04-20 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0023_alter_backlogged_date_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backlogged',
            unique_together={('user', 'game')},
        ),
    ]
