# Generated by Django 4.1.5 on 2023-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date_backlogged',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='date_started',
            field=models.DateField(null=True),
        ),
    ]
