# Generated by Django 4.1.5 on 2023-08-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_library_date_backlogged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[], default='backlog', max_length=10),
        ),
    ]
