# Generated by Django 4.1.5 on 2023-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_remove_library_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[(0, 'backlog'), (1, 'playing'), (2, 'completed')], default=2, max_length=10),
        ),
    ]
