# Generated by Django 4.1.5 on 2023-08-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_library_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('backlog', 'playing'), ('backlog', 'completed')], default=2, max_length=10),
        ),
    ]
