# Generated by Django 4.1.5 on 2023-08-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_alter_library_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='status',
        ),
    ]
