# Generated by Django 4.1.5 on 2023-08-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_remove_library_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('playing', 'playing'), ('completed', 'completed')], default='completed', max_length=10),
        ),
    ]
