# Generated by Django 4.1.5 on 2023-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_alter_library_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in CAD after tax and discounts.', max_digits=6, null=True),
        ),
    ]
