# Generated by Django 4.1.5 on 2023-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_library_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
