# Generated by Django 4.1.5 on 2023-09-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_library_date_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing',
            name='backlog',
        ),
        migrations.RemoveField(
            model_name='playing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='backlog',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='user',
        ),
        migrations.DeleteModel(
            name='Backlogged',
        ),
        migrations.DeleteModel(
            name='Playing',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
