# Generated by Django 4.1.5 on 2025-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_remove_playing_backlog_remove_playing_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='platform_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='platform_playdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='platform_playstation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='platform_steam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='platform_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='platform_xbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('playing', 'playing'), ('completed', 'completed'), ('retired', 'retired')], default='backlog', max_length=10),
        ),
    ]
